name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Change to src directory
      run: cd src

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t hiranjanperera/git-api-flask -f src/Dockerfile .

    - name: Run API tests
      run: |
        docker run -d --name api-test -p 5000:5000 hiranjanperera/git-api-flask
        python src/test_app.py
        docker stop api-test

    - name: Push to Dockerhub
      if: success()
      run: docker push hiranjanperera/git-api-flask:latest
