name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask requests  

    - name: Run tests
      run: |
        python src/test_app.py  

    
    - name: Change to src directory
      run: cd src

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t hiranjanperera/git-api-flask -f src/Dockerfile .


    - name: Push to Dockerhub
      run: docker push hiranjanperera/git-api-flask:latest
